BEGIN:VCALENDAR
VERSION:2.0
PRODID:ics.py - http://git.io/lLljaA
BEGIN:VEVENT
DESCRIPTION:https://transportnsw.info/alerts/details#/ems-63760\n\nThursday 1 January From 9 10 AM to 2 PM\, buses replace trains between Wollongong and Port Kembla.
DTEND:20260101T030000Z
DTSTART:20251231T221000Z
SUMMARY:Buses replace trains between Wollongong and Port Kembla
UID:878658cc-e0c9-5677-b868-76e7cb8ed51b
URL:https://transportnsw.info/alerts/details#/ems-63760
END:VEVENT
END:VCALENDAR